#!/bin/bash

VALID=0

while [ $VALID -eq 0 ]
do
    read -p "Please enter your name and age: " NAME AGE
    if [[ ( -z $NAME ) || ( -z $AGE ) ]]
    then
        echo "not enough parameters passed"
        continue
    # =~ is regular expression match operator.
    elif [[ ! $NAME =~ ^[a-zA-Z]+$ ]]
    then
        echo "non alpha characters detected [$NAME]"
        continue
    elif [[ ! $AGE =~ ^[0-9]+$ ]]
    then
        echo "non digit characters detected [$AGE]"
        continue
    fi
    VALID=1
done

echo "Name = $NAME and age = $AGE"
exit 0
