#!/bin/sh
#
# Script to see whether argument is positive
#
if test $1 -gt 0
#or
#if [ $1 > 0 ]
then
	echo "$1 number is positive"
fi

#
# -eq	is equal to  
# -ne	is not equal to
# -It	is less than
# -le	is less than or equal to
# -gt	is greater than
# -ge	is greater than or equal to
#

if [ $1 -eq 5 ] 
then
	echo "first argument is equal to 5"
elif [ $1 = 6 ]
then
	echo "first argument is 6"
elif [ $1 != 7 ]
then
	echo "but it's not 7!"
fi
