#!/bin/bash
# if no vehicle name is given
# i.e. -z $1 is defined and it is NULL
#
if [ -z $1 ] # means null or does not exist
then
    rental="*** Unknown vehicle ***"
elif [ -n $1 ] # is not null and does exist
then
    rental=$1
fi

case $rental in
    "car") echo "For $rental Rs.20 per k/m";;
    "van") echo "For $rental Rs.10 per k/m";;
    "jeep") echo "For $rental Rs.5 per k/m";;
    *) echo "Sorry, I can not get a $rental for you";;
esac
