#!/bin/bash
#
#Script to test while statement
#
if [ $# -eq 0 ]
then
    echo "Error - Number missing from command line argument"
    exit 1
fi

n=$1
i=1
while [ $i -le 10 ]
do
    echo "$n * $i = `expr $i \* $n`"
    i=`expr $i + 1`
    #or
    #(( i++ ))
done
